/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.SalaryDAO;
import exception.PaidException;
import javax.swing.JOptionPane;
import model.Manager;
import model.Salary;

/**
 *
 * @author nguye
 */
public class ConfirmFrm extends javax.swing.JFrame {

    private Manager manager;
    private Salary salary;
    /**
     * Creates new form ConfirmFrm
     */
    public ConfirmFrm(Manager m, Salary s) {
        initComponents();
        this.setLocationRelativeTo(null);
        lblEmployee.setText("Nhân viên: " + s.getListWorkedShift().get(0).getEmployee().getName());
        lblInShiftSalary.setText("Số tiền trong ca: " + s.getSumInShiftSalary());
        lblOutShiftSalary.setText("Số tiền thừa ca: " + s.getSumOutShiftSalary());
        lblBonus.setText("Tiền thưởng: " + s.getBonus());
        lblLateFee.setText("Tiền phạt: " + s.getSumLateFee());
        lblAllowance.setText("Trợ cấp: " + s.getAllowance());
        lblRealSalary.setText("Thực nhận: " + s.getRealSalary());
        
        this.salary = s;
        this.manager = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        lblInShiftSalary = new javax.swing.JLabel();
        lblOutShiftSalary = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        lblRealSalary = new javax.swing.JLabel();
        lblAllowance = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        lblLateFee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("Xác nhận thanh toán?");

        lblEmployee.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(0, 0, 153));
        lblEmployee.setText("Nhân viên:");

        lblInShiftSalary.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblInShiftSalary.setForeground(new java.awt.Color(0, 0, 153));
        lblInShiftSalary.setText("Số tiền trong ca:");

        lblOutShiftSalary.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblOutShiftSalary.setForeground(new java.awt.Color(0, 0, 153));
        lblOutShiftSalary.setText("Số tiền thừa ca:");

        lblBonus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblBonus.setForeground(new java.awt.Color(0, 0, 153));
        lblBonus.setText("Tiền thưởng:");

        lblRealSalary.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRealSalary.setForeground(new java.awt.Color(0, 0, 153));
        lblRealSalary.setText("Thực nhận:");

        lblAllowance.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAllowance.setForeground(new java.awt.Color(0, 0, 153));
        lblAllowance.setText("Trợ cấp:");

        btnConfirm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(0, 0, 153));
        btnConfirm.setText("Xác nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(0, 0, 153));
        btnReturn.setText("Hủy");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        lblLateFee.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblLateFee.setForeground(new java.awt.Color(0, 0, 153));
        lblLateFee.setText("Tiền phạt:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInShiftSalary)
                            .addComponent(lblEmployee)
                            .addComponent(lblBonus)
                            .addComponent(lblRealSalary)
                            .addComponent(lblOutShiftSalary)
                            .addComponent(lblAllowance)
                            .addComponent(lblLateFee))))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addComponent(lblEmployee)
                .addGap(18, 18, 18)
                .addComponent(lblInShiftSalary)
                .addGap(18, 18, 18)
                .addComponent(lblOutShiftSalary)
                .addGap(18, 18, 18)
                .addComponent(lblBonus)
                .addGap(18, 18, 18)
                .addComponent(lblLateFee)
                .addGap(18, 18, 18)
                .addComponent(lblAllowance)
                .addGap(18, 18, 18)
                .addComponent(lblRealSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        SalaryDAO sd = new SalaryDAO();
        try {
            if(!sd.updateSalary(salary)) 
                throw new PaidException("Lương của nhân viên này đã được thanh toán rồi!");
            JOptionPane.showMessageDialog(this, "Lưu thanh toán thành công");
            new ManagerHomeFrm(manager).setVisible(true);
        } catch(PaidException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            this.dispose();
            new ManagerHomeFrm(manager).setVisible(true);
        }
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DetailSalaryFrm(manager, salary).setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAllowance;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblInShiftSalary;
    private javax.swing.JLabel lblLateFee;
    private javax.swing.JLabel lblOutShiftSalary;
    private javax.swing.JLabel lblRealSalary;
    // End of variables declaration//GEN-END:variables
}
